{ config, pkgs, lib, user, homeDir, nix-secrets, ... }:

let
  isLinux = pkgs.stdenv.isLinux;
  isWorkUser = user == "mtr21pqh";
in {
  programs.ssh = {
    enable = true;
    enableDefaultConfig = false;
    settings = {
      "*" = {
        SendEnv = "LANG LC_*";
        HashKnownHosts = true;
        AddKeysToAgent = "yes";
        ControlMaster = "auto";
        ControlPath = "~/.ssh/sockets/%r@%h-%p.%C";
        ControlPersist = "600";
      };
      "github.com" = {
        IdentitiesOnly = true;
        IdentityFile = if isLinux then "/home/${user}/.ssh/id_mgrbyte_github" else "/Users/${user}/.ssh/id_mgrbyte_github";
      };
    };
  };

  # Redirect HM-generated SSH config to a staging path so ~/.ssh/config
  # is free for activation-time composition with the decrypted work config.
  # Fabric/Paramiko don't support Include directives, so we inline instead.
  home.file.".ssh/config".target = ".ssh/config_base";

  # Compose ~/.ssh/config by concatenating the decrypted work config
  # with the base config generated by home-manager.
  home.activation.composeSshConfig =
    lib.hm.dag.entryAfter [ "linkGeneration" ] ''
      _base="${homeDir}/.ssh/config_base"
      _target="${homeDir}/.ssh/config"

      if [[ -f "$_base" ]] || [[ -L "$_base" ]]; then
        rm -f "$_target"
        {
          ${lib.optionalString isWorkUser ''
          ${pkgs.rage}/bin/rage --decrypt \
            -i ${homeDir}/.ssh/id_ed25519_agenix \
            -o - \
            ${nix-secrets}/ssh-config-work.age
          printf '\n'
          ''}
          cat "$_base"
        } > "$_target"
        chmod 0600 "$_target"
      fi
    '';

  home.activation.ensureSshSocketsDir = lib.hm.dag.entryAfter ["writeBoundary"] ''
    mkdir -p ${homeDir}/.ssh/sockets
  '';

  # Reload agent keys from the macOS Keychain whenever the agent (re)starts.
  # The zshrc loader only fires on new interactive shells, so an agent restart
  # mid-session leaves long-lived contexts (tmux, emacs/magit) with an empty
  # agent. Apple's launchd ssh-agent creates a fresh socket under ~/.ssh/agent
  # on start; WatchPaths turns that into the reload trigger. Must be Apple's
  # /usr/bin/ssh-add — the nix ssh-add has no Keychain support.
  launchd.agents.ssh-load-keychain = lib.mkIf pkgs.stdenv.isDarwin {
    enable = true;
    config = {
      ProgramArguments = [ "/usr/bin/ssh-add" "--apple-load-keychain" ];
      RunAtLoad = true;
      WatchPaths = [ "${homeDir}/.ssh/agent" ];
      StandardOutPath = "${homeDir}/.cache/ssh-load-keychain.log";
      StandardErrorPath = "${homeDir}/.cache/ssh-load-keychain.log";
    };
  };
}
